server {
    listen 80;
    server_name vm165550.evps.zone;

    location / {
        root /var/www/html/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        try_files $uri $uri/ @laravel;
    }

    location @laravel {
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        
        fastcgi_param SCRIPT_FILENAME /var/www/html/backend/public/index.php;
        
        include fastcgi_params;
        
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param QUERY_STRING $query_string;
    }

    location ~ /\.ht {
        deny all;
    }
    
    location ~ /\.env {
        deny all;
    }
    
    location ~ /vendor/ {
        deny all;
    }
}
